wandb_version: 1

dataset:
  desc: null
  value: pneumoniamnist
model:
  desc: null
  value: vit_timm
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0001
resize:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723942665
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.17.6
      6: 4.43.3
      8:
      - 5
      13: darwin-arm64
